# Generated by Django 4.1.2 on 2022-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag_status',
            field=models.CharField(choices=[('Feestganger', 'Feestganger'), ('Feestbeest', 'Feestbeest'), ('Eigenaar', 'Eigenaar'), ('Manager', 'Manager'), ('Promoter', 'Promoter')], default='Feestganger', max_length=20),
        ),
    ]
