# Generated by Django 4.1.2 on 2022-10-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussin', '0004_party_slug_alter_organisation_kvk_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='party',
        ),
        migrations.AddField(
            model_name='category',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bussin.party'),
            preserve_default=False,
        ),
    ]
