# Generated by Django 4.1.2 on 2022-10-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussin', '0009_category_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussin.party'),
        ),
    ]
