# Generated by Django 4.1.3 on 2022-11-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussin', '0011_role_remove_profile_tag_status_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Party Person'), (2, 'Raver'), (3, 'Pro Raver'), (4, 'Promoter'), (6, 'Accountant')], primary_key=True, serialize=False),
        ),
    ]
